### PR TITLE
Initial example

### PR DESCRIPTION
**Pull request by JuanM04**

### CODE REVIEW

**Comment by gamedevsam** [comment]
Can we get this merged? Seems like some code would be better than no code :-P

**Comment by olof-nord** [comment]
> 
> 
> Can we get this merged? Seems like some code would be better than no code :-P

I can only agree to this.

What, if anything, is holding this PR back?

**Comment by jackHedaya** [comment]
Bump

**Comment by lluia** [comment]
Super sorry for the review delay on this 🙏🏽

@JuanM04 closing this PR, I had a pair-programming session with @balazsorban44, and we pushed the code directly to `main` 👍🏽 .

This fits as part of the effort we're doing to bring better **TS** support and DX on `next-auth`:
- https://github.com/nextauthjs/next-auth/issues/1650
- https://github.com/nextauthjs/next-auth/issues/1649

Thanks a lot though for the initiative ❤️ 💯

**Comment by balazsorban44** [comment]
Better later than never. 😂

**Pull request closed without merging**
